// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWMEIf1Bw3c_ap68IfR40r1LObm6HmlEw',
    appId: '1:488213629760:web:2983b07235e667725388a5',
    messagingSenderId: '488213629760',
    projectId: 'bits-shop',
    authDomain: 'bits-shop.firebaseapp.com',
    storageBucket: 'bits-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_eQKmzy2A7mMZKkH5HAolCH-ONcvRJeA',
    appId: '1:488213629760:android:02b03bbd907635fe5388a5',
    messagingSenderId: '488213629760',
    projectId: 'bits-shop',
    storageBucket: 'bits-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC94bgkTpfmCSPaZEdG3bXxG5-l0B0fLo',
    appId: '1:488213629760:ios:f83aabb608eeac435388a5',
    messagingSenderId: '488213629760',
    projectId: 'bits-shop',
    storageBucket: 'bits-shop.appspot.com',
    iosClientId: '488213629760-8sr5rvsjdl178igplitnbjl5q4hkaq2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
